name: Deploy Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Build documentation
        run: |
          # Create docs directory
          mkdir -p docs-site

          # Copy documentation files
          cp README.md docs-site/
          cp docs/* docs-site/

          # Create index.html for GitHub Pages
          cat > docs-site/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Reactive-DOM Documentation</title>
              <style>
                  body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
                  h1 { color: #333; border-bottom: 2px solid #007bff; }
                  h2 { color: #007bff; }
                  code { background: #f4f4f4; padding: 2px 4px; border-radius: 3px; }
                  pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
                  .nav { background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; }
                  .nav a { margin-right: 15px; text-decoration: none; color: #007bff; }
                  .nav a:hover { text-decoration: underline; }
              </style>
          </head>
          <body>
              <h1>Reactive-DOM Documentation</h1>
              <div class="nav">
                  <a href="README.md">README</a>
                  <a href="API.md">API Reference</a>
                  <a href="DEVELOPMENT.md">Development Guide</a>
              </div>
              <p>Welcome to the Reactive-DOM documentation. Choose a link above to get started.</p>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-site
          publish_branch: gh-pages
